<div class="info">
    <h3>All Pending Students</h3>
    <table class="table table-striped table-hover table-border" height="100%" width="50%">
        <tr>
            <th>S.No</th>
            <th>Name</th>
            <th>E-mail</th>
        </tr>
        <tr>
            <td>1.</td>
            <td>Aditya</td>
            <td>aditya@gmail.com</td>
        </tr>
        <tr>
            <td>2.</td>
            <td>Arjun</td>
            <td>arjun@gmail.com</td>
        </tr>
        <tr>
            <td>3.</td>
            <td>Gokul</td>
            <td>gokul@gmail.com</td>
        </tr>
        <tr>
            <td>4.</td>
            <td>Kavya</td>
            <td>kavya@gmail.com</td>
        </tr>
        <tr>
            <td>5.</td>
            <td>Radhika</td>
            <td>radhika@gmail.com</td>
        </tr>
        <tr>
            <td>6.</td>
            <td>Manoj</td>
            <td>manoj@gmail.com</td>
        </tr>
    </table>
</div>